import { Router } from "express";
import { requirePermission } from "../workspaces/workspace-context.js";
import * as c from "./cards.controller.js";
const r = Router({ mergeParams: true });
r.get("/", requirePermission("debts.read"), c.list);
r.post("/", requirePermission("debts.write"), c.create);
r.patch("/:cardId", requirePermission("debts.write"), c.update);
r.delete("/:cardId", requirePermission("debts.write"), c.remove);
r.post("/:cardId/cash-advances", requirePermission("debts.write"), c.cashAdvance);
r.get("/:cardId/activity", requirePermission("debts.read"), c.activity);
r.get("/:cardId/purchases", requirePermission("debts.read"), c.purchases);
r.post("/:cardId/purchases", requirePermission("debts.write"), c.purchase);
r.get("/:cardId/statements", requirePermission("debts.read"), c.statements);
r.post("/:cardId/statements", requirePermission("debts.write"), c.statement);
r.post("/:cardId/next-payment", requirePermission("debts.write"), c.nextPayment);
r.post("/:cardId/statements/:statementId/payments", requirePermission("debts.write"), c.pay);
r.post("/:cardId/payments", requirePermission("debts.write"), c.payBalance);
export default r;
