import { Router } from "express";
import { requirePermission } from "../workspaces/workspace-context.js";
import * as controller from "./budgets.controller.js";
const router = Router({ mergeParams: true });
router.get("/", requirePermission("budgets.read"), controller.list);
router.get("/:budgetId", requirePermission("budgets.read"), controller.get);
router.post("/", requirePermission("budgets.write"), controller.create);
router.patch("/:budgetId", requirePermission("budgets.write"), controller.update);
router.delete("/:budgetId", requirePermission("budgets.write"), controller.archive);
router.post("/:budgetId/restore", requirePermission("budgets.write"), controller.restore);
export default router;
