export const AUTH_PASSWORD_MEMORY_COST_MIN = 19_456;
export const AUTH_PASSWORD_MEMORY_COST_MAX = 1_048_576;
export const AUTH_PASSWORD_MEMORY_COST_DEFAULT = 65_536;

export const AUTH_PASSWORD_TIME_COST_MIN = 2;
export const AUTH_PASSWORD_TIME_COST_MAX = 10;
export const AUTH_PASSWORD_TIME_COST_DEFAULT = 3;

export const AUTH_PASSWORD_PARALLELISM_MIN = 1;
export const AUTH_PASSWORD_PARALLELISM_MAX = 16;
export const AUTH_PASSWORD_PARALLELISM_DEFAULT = 1;
