CREATE TABLE "issued_loans" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "workspace_id" UUID NOT NULL,
  "person_id" UUID NOT NULL,
  "receivable_account_id" UUID NOT NULL,
  "source_account_id" UUID,
  "currency" CHAR(3) NOT NULL,
  "original_principal" DECIMAL(18,2) NOT NULL,
  "current_principal" DECIMAL(18,2) NOT NULL,
  "rate_percent" DECIMAL(10,7) NOT NULL,
  "method" VARCHAR(30) NOT NULL,
  "frequency" VARCHAR(20) NOT NULL,
  "term_count" INTEGER NOT NULL,
  "installment_amount" DECIMAL(18,2) NOT NULL,
  "expected_interest" DECIMAL(18,2) NOT NULL,
  "expected_total" DECIMAL(18,2) NOT NULL,
  "principal_received" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "interest_received" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "disbursement_date" DATE NOT NULL,
  "first_payment_date" DATE NOT NULL,
  "next_due_date" DATE,
  "estimated_end_date" DATE NOT NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  "notes" TEXT,
  "created_by" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "archived_at" TIMESTAMPTZ,
  CONSTRAINT "issued_loans_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "issued_loans_workspace_id_id_key" UNIQUE ("workspace_id", "id"),
  CONSTRAINT "issued_loans_amounts_check" CHECK ("original_principal" > 0 AND "current_principal" >= 0 AND "rate_percent" >= 0 AND "term_count" > 0),
  CONSTRAINT "issued_loans_method_check" CHECK ("method" IN ('FIXED_PAYMENT','FIXED_PRINCIPAL','INTEREST_ONLY')),
  CONSTRAINT "issued_loans_frequency_check" CHECK ("frequency" IN ('WEEKLY','BIWEEKLY','MONTHLY')),
  CONSTRAINT "issued_loans_status_check" CHECK ("status" IN ('ACTIVE','OVERDUE','PAID','ARCHIVED')),
  CONSTRAINT "issued_loans_workspace_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE,
  CONSTRAINT "issued_loans_person_fkey" FOREIGN KEY ("workspace_id", "person_id") REFERENCES "financial_people"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loans_receivable_fkey" FOREIGN KEY ("workspace_id", "receivable_account_id") REFERENCES "financial_accounts"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loans_source_fkey" FOREIGN KEY ("workspace_id", "source_account_id") REFERENCES "financial_accounts"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loans_creator_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT
);

CREATE TABLE "issued_loan_installments" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "workspace_id" UUID NOT NULL,
  "loan_id" UUID NOT NULL,
  "installment_number" INTEGER NOT NULL,
  "due_date" DATE NOT NULL,
  "opening_principal" DECIMAL(18,2) NOT NULL,
  "principal_amount" DECIMAL(18,2) NOT NULL,
  "interest_amount" DECIMAL(18,2) NOT NULL,
  "total_amount" DECIMAL(18,2) NOT NULL,
  "principal_paid" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "interest_paid" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "total_paid" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "closing_principal" DECIMAL(18,2) NOT NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  "paid_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "issued_loan_installments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "issued_loan_installments_workspace_id_id_key" UNIQUE ("workspace_id", "id"),
  CONSTRAINT "issued_loan_installments_number_key" UNIQUE ("workspace_id", "loan_id", "installment_number"),
  CONSTRAINT "issued_loan_installments_status_check" CHECK ("status" IN ('PENDING','PARTIAL','OVERDUE','PAID')),
  CONSTRAINT "issued_loan_installments_amounts_check" CHECK ("principal_amount" >= 0 AND "interest_amount" >= 0 AND "total_paid" >= 0 AND "total_paid" <= "total_amount"),
  CONSTRAINT "issued_loan_installments_loan_fkey" FOREIGN KEY ("workspace_id", "loan_id") REFERENCES "issued_loans"("workspace_id", "id") ON DELETE CASCADE
);

CREATE TABLE "issued_loan_payments" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "workspace_id" UUID NOT NULL,
  "loan_id" UUID NOT NULL,
  "installment_id" UUID NOT NULL,
  "receiving_account_id" UUID NOT NULL,
  "principal_transaction_id" UUID,
  "interest_transaction_id" UUID,
  "total_received" DECIMAL(18,2) NOT NULL,
  "principal_received" DECIMAL(18,2) NOT NULL,
  "interest_received" DECIMAL(18,2) NOT NULL,
  "occurred_at" TIMESTAMPTZ NOT NULL,
  "notes" TEXT,
  "idempotency_key" VARCHAR(120) NOT NULL,
  "created_by" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "reversed_at" TIMESTAMPTZ,
  "reversed_by" UUID,
  "reversal_reason" VARCHAR(500),
  CONSTRAINT "issued_loan_payments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "issued_loan_payments_idempotency_key" UNIQUE ("workspace_id", "idempotency_key"),
  CONSTRAINT "issued_loan_payments_amounts_check" CHECK ("total_received" > 0 AND "principal_received" >= 0 AND "interest_received" >= 0 AND "total_received" = "principal_received" + "interest_received"),
  CONSTRAINT "issued_loan_payments_loan_fkey" FOREIGN KEY ("workspace_id", "loan_id") REFERENCES "issued_loans"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loan_payments_installment_fkey" FOREIGN KEY ("workspace_id", "installment_id") REFERENCES "issued_loan_installments"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loan_payments_receiving_fkey" FOREIGN KEY ("workspace_id", "receiving_account_id") REFERENCES "financial_accounts"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loan_payments_principal_transaction_fkey" FOREIGN KEY ("workspace_id", "principal_transaction_id") REFERENCES "transactions"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loan_payments_interest_transaction_fkey" FOREIGN KEY ("workspace_id", "interest_transaction_id") REFERENCES "transactions"("workspace_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loan_payments_creator_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT,
  CONSTRAINT "issued_loan_payments_reverser_fkey" FOREIGN KEY ("reversed_by") REFERENCES "users"("id") ON DELETE RESTRICT
);

CREATE INDEX "issued_loans_workspace_status_due_idx" ON "issued_loans"("workspace_id", "status", "next_due_date");
CREATE INDEX "issued_loans_workspace_person_idx" ON "issued_loans"("workspace_id", "person_id");
CREATE INDEX "issued_installments_workspace_due_idx" ON "issued_loan_installments"("workspace_id", "due_date", "status");
CREATE INDEX "issued_payments_workspace_loan_idx" ON "issued_loan_payments"("workspace_id", "loan_id", "occurred_at" DESC);
