import { Router } from "express";
import { authenticate } from "../../common/middlewares/authenticate.js";
import { resolveWorkspaceContext } from "./workspace-context.js";
import * as controller from "./workspaces.controller.js";
import accountsRouter from "../accounts/accounts.routes.js";
import categoriesRouter from "../categories/categories.routes.js";
import transactionsRouter from "../transactions/transactions.routes.js";
import dashboardRouter from "../dashboard/dashboard.routes.js";
import budgetsRouter from "../budgets/budgets.routes.js";
import reportsRouter from "../reports/reports.routes.js";
import forecastsRouter from "../forecasts/forecasts.routes.js";
import debtsRouter from "../debts/debts.routes.js";
import obligationsRouter from "../obligations/obligations.routes.js";
import cardsRouter from "../cards/cards.routes.js";
import liabilitiesRouter from "../liabilities/liabilities.routes.js";
import personalBalancesRouter from "../personal-balances/personal-balances.routes.js";
import lendingRouter from "../lending/lending.routes.js";
import goalsRouter from "../goals/goals.routes.js";

const router = Router();
router.use(authenticate);
router.get("/", controller.list);
router.use("/:workspaceId/accounts", resolveWorkspaceContext, accountsRouter);
router.use("/:workspaceId/categories", resolveWorkspaceContext, categoriesRouter);
router.use("/:workspaceId/transactions", resolveWorkspaceContext, transactionsRouter);
router.use("/:workspaceId/dashboard", resolveWorkspaceContext, dashboardRouter);
router.use("/:workspaceId/budgets", resolveWorkspaceContext, budgetsRouter);
router.use("/:workspaceId/reports", resolveWorkspaceContext, reportsRouter);
router.use("/:workspaceId/forecasts", resolveWorkspaceContext, forecastsRouter);
router.use("/:workspaceId/debts", resolveWorkspaceContext, debtsRouter);
router.use("/:workspaceId/obligations", resolveWorkspaceContext, obligationsRouter);
router.use("/:workspaceId/cards", resolveWorkspaceContext, cardsRouter);
router.use("/:workspaceId/goals", resolveWorkspaceContext, goalsRouter);
router.use("/:workspaceId/personal-balances", resolveWorkspaceContext, personalBalancesRouter);
router.use("/:workspaceId/lending", resolveWorkspaceContext, lendingRouter);
router.use("/:workspaceId", resolveWorkspaceContext, liabilitiesRouter);
router.get("/:workspaceId", resolveWorkspaceContext, controller.get);
router.post("/:workspaceId/select", resolveWorkspaceContext, controller.select);
export default router;
